name: mosaique_example
description: Example app demonstrating the Mosaique package
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.2
  mosaique:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
